blank_issues_enabled: false
contact_links:
  - name: 💬 질문 / 토론
    url: https://github.com/ColdPassDevelopmentTeam/computer-science-study-2nd/discussions
    about: 개념 질문이나 함께 논의할 내용은 Discussions에서 자유롭게 공유해주세요.
